"""初始建表：9 张表

Revision ID: 0fbeec2c89e7
Revises: 
Create Date: 2026-06-09 14:34:52.433697
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fbeec2c89e7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alarm_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('test_id', sa.String(), nullable=True),
    sa.Column('alarm_code', sa.String(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('occur_time', sa.Text(), nullable=False),
    sa.Column('clear_time', sa.Text(), nullable=True),
    sa.Column('ack_time', sa.Text(), nullable=True),
    sa.Column('ack_operator', sa.String(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('latched', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alarm_log', schema=None) as batch_op:
        batch_op.create_index('idx_al_occur', ['occur_time'], unique=False)

    op.create_table('device_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.Text(), nullable=False),
    sa.Column('status_json', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device_status', schema=None) as batch_op:
        batch_op.create_index('idx_ds_ts', ['ts'], unique=False)

    op.create_table('event_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('test_id', sa.String(), nullable=True),
    sa.Column('ts', sa.Text(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('event_code', sa.String(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('operator_id', sa.String(), nullable=True),
    sa.Column('detail_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event_log', schema=None) as batch_op:
        batch_op.create_index('idx_el_test', ['test_id'], unique=False)
        batch_op.create_index('idx_el_ts', ['ts'], unique=False)

    op.create_table('operator_action',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.Text(), nullable=False),
    sa.Column('operator_id', sa.String(), nullable=False),
    sa.Column('operator_role', sa.String(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('test_id', sa.String(), nullable=True),
    sa.Column('params_json', sa.Text(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('reason_code', sa.Text(), nullable=True),
    sa.Column('client_ip', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parameter_snapshot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('test_id', sa.String(), nullable=True),
    sa.Column('ts', sa.Text(), nullable=False),
    sa.Column('operator_id', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('fw_version', sa.Text(), nullable=True),
    sa.Column('profile_version', sa.Text(), nullable=True),
    sa.Column('param_crc', sa.Text(), nullable=True),
    sa.Column('params_json', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_export',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('test_id', sa.String(), nullable=False),
    sa.Column('generated_at', sa.Text(), nullable=False),
    sa.Column('operator_id', sa.String(), nullable=False),
    sa.Column('format', sa.String(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sample_point',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('test_id', sa.String(), nullable=False),
    sa.Column('ts', sa.Text(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('furnace_pv', sa.Float(), nullable=True),
    sa.Column('furnace_sv', sa.Float(), nullable=True),
    sa.Column('burden_temp', sa.Float(), nullable=True),
    sa.Column('burden_temp_v', sa.Integer(), nullable=False),
    sa.Column('temp_output_pct', sa.Float(), nullable=True),
    sa.Column('program_step', sa.Integer(), nullable=True),
    sa.Column('n2_sp', sa.Float(), nullable=True),
    sa.Column('n2_pv', sa.Float(), nullable=True),
    sa.Column('co_sp', sa.Float(), nullable=True),
    sa.Column('co_pv', sa.Float(), nullable=True),
    sa.Column('drip_weight', sa.Float(), nullable=True),
    sa.Column('delta_p', sa.Float(), nullable=True),
    sa.Column('delta_p_v', sa.Integer(), nullable=False),
    sa.Column('displacement', sa.Float(), nullable=True),
    sa.Column('displacement_v', sa.Integer(), nullable=False),
    sa.Column('current_state', sa.Text(), nullable=True),
    sa.Column('safety_relay', sa.Integer(), nullable=True),
    sa.Column('ext_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sample_point', schema=None) as batch_op:
        batch_op.create_index('idx_sp_test_ts', ['test_id', 'ts'], unique=False)

    op.create_table('test_session',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('test_id', sa.String(), nullable=False),
    sa.Column('operator_id', sa.String(), nullable=False),
    sa.Column('start_time', sa.Text(), nullable=False),
    sa.Column('end_time', sa.Text(), nullable=True),
    sa.Column('end_reason', sa.Text(), nullable=True),
    sa.Column('state_at_end', sa.Text(), nullable=True),
    sa.Column('sample_label', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('report_path', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('test_id')
    )
    op.create_table('user_account',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_pw', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('last_login', sa.Text(), nullable=True),
    sa.CheckConstraint("role IN ('observer','operator','admin','maintainer')", name='ck_user_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_account')
    op.drop_table('test_session')
    with op.batch_alter_table('sample_point', schema=None) as batch_op:
        batch_op.drop_index('idx_sp_test_ts')

    op.drop_table('sample_point')
    op.drop_table('report_export')
    op.drop_table('parameter_snapshot')
    op.drop_table('operator_action')
    with op.batch_alter_table('event_log', schema=None) as batch_op:
        batch_op.drop_index('idx_el_ts')
        batch_op.drop_index('idx_el_test')

    op.drop_table('event_log')
    with op.batch_alter_table('device_status', schema=None) as batch_op:
        batch_op.drop_index('idx_ds_ts')

    op.drop_table('device_status')
    with op.batch_alter_table('alarm_log', schema=None) as batch_op:
        batch_op.drop_index('idx_al_occur')

    op.drop_table('alarm_log')
    # ### end Alembic commands ###
